name: Run cron jobs

on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '0 17 * * 4'

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Execute reviews task
        run: curl -X GET https://egc-hecker-server-kubqn-kubqns-projects.vercel.app/api/cron/reviews.js

      - name: Execute weekly task
        run: curl -X GET https://egc-hecker-server-kubqn-kubqns-projects.vercel.app/api/cron/weeklyGames.js
